services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true # Désactive la sécurité pour tes tests locaux
    ports:
      - "9200:9200"
      - "9600:9600"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - opensearch-network
    volumes:
      - opensearch_data:/usr/share/opensearch/data

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.11.0
    container_name: opensearch-dashboards
    environment:
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
      - OPENSEARCH_HOSTS=http://opensearch:9200
    ports:
      - "5601:5601" # Même port que Kibana !
    depends_on:
      opensearch:
        condition: service_healthy
    networks:
      - opensearch-network

networks:
  opensearch-network:
    driver: bridge

volumes:
  opensearch_data:
    driver: local