spring.application.name=testelasticsearch
spring.opensearch.uris=${ELASTICSEARCH_URL}
spring.opensearch.username=${ELASTICSEARCH_USERNAME}
spring.opensearch.password=${ELASTICSEARCH_PASSWORD}
spring.opensearch.ssl.verification-mode=none
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.auto-index-creation=false

# --- CONFIGURATION POSTGRESQL ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
