spring.application.name=testelasticsearch
spring.elasticsearch.uris=http://localhost:9200
spring.elasticsearch.ssl.verification-mode=none
spring.data.elasticsearch.repositories.enabled=true
spring.data.elasticsearch.auto-index-creation=false

# --- CONFIGURATION POSTGRESQL ---
spring.datasource.url=jdbc:postgresql://localhost:5434/book_db
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
